# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2023
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "🔧"
subtitle = "Fixing what I don't consider perfect"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
math = false
readingTime = true

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = true
local = true
src = "img/avatar.png"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "vyPal/vyPal.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkyOTM4Mjk1ODI="
category = "General"
categoryID = "DIC_kwDOEYN7zs4Cb6KY"
mapping = "pathname"
lightTheme = "0"
darkTheme = "1"
reactionsEnabled = 1
emitMetadata = 0

[services.umami_analytics]
id = '7b165982-1021-46e6-aa14-d99fc5049972'
script_url = 'https://umami.vypal.me/script.js'
